INSERT INTO ROLE
(
ROLE_ID, ROLE_NAME
) VALUES
(
1, 'ADMINISTRATOR'
);

INSERT INTO MEMBER
(
 MEMBER_ID, MEMBER_NAME, MEMBER_STATE, GRADE, NICK_NAME, ROLE_ID
 , SNS_LOGIN_YN, EMAIL, GENDER, PROFILE_IMAGE_PATH, MOBILE
 , UID, BANNED_YN, PASSWORD, LOGIN_FAIL_COUNT
 ) VALUES
(
 1, 'admin', 'NORMAL', 'DIAMOND', 'admin', 1
 , FALSE, 'admin@joomak.corp', 'MALE', 'src', '010-2604-7521'
 , '1234567890', 'N', '$2a$12$G/.qihiiHcQwHeObQuudDuj4zaaqacjTlhh16yMk8Uy.zmqO5Rwq6', 0
);
